In [28]:
import torch
import torch.nn.functional as F
import numpy as np

初始化输入向量

In [2]:
x = [
  [1, 0, 1, 0], # Input 1
  [0, 2, 0, 2], # Input 2
  [1, 1, 1, 1]  # Input 3
 ]
x = torch.tensor(x, dtype=torch.float32)
x

tensor([[1., 0., 1., 0.],
        [0., 2., 0., 2.],
        [1., 1., 1., 1.]])

初始化Wk，Wq，Wv矩阵。

In [18]:
Wk = torch.tensor([
  [0, 0, 1],
  [1, 1, 0],
  [0, 1, 0],
  [1, 1, 0]
], dtype=torch.float32)
Wq = torch.tensor([
  [1, 0, 1],
  [1, 0, 0],
  [0, 0, 1],
  [0, 1, 1]
], dtype=torch.float32)
Wv = torch.tensor([
  [0, 2, 0],
  [0, 3, 0],
  [1, 0, 3],
  [1, 1, 0]
], dtype=torch.float32)

生成K向量

In [19]:
K = torch.matmul(x, Wk)
K

tensor([[0., 1., 1.],
        [4., 4., 0.],
        [2., 3., 1.]])

生成Q向量

In [20]:
Q = torch.matmul(x, Wq)
Q

tensor([[1., 0., 2.],
        [2., 2., 2.],
        [2., 1., 3.]])

生成V向量

In [21]:
V = torch.matmul(x, Wv)
V

tensor([[1., 2., 3.],
        [2., 8., 0.],
        [2., 6., 3.]])

完成attention计算

In [23]:
weight = F.softmax(K @ Q.T)
weight

<ipython-input-23-11533ce7f6bd>:1: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  weight = F.softmax(K @ Q.T)


tensor([[6.3379e-02, 4.6831e-01, 4.6831e-01],
        [6.0337e-06, 9.8201e-01, 1.7986e-02],
        [2.9539e-04, 8.8054e-01, 1.1917e-01]])

In [24]:
# For readability, approximate the above as follows
weight = [
  [0.0, 0.5, 0.5],
  [0.0, 1.0, 0.0],
  [0.0, 0.9, 0.1]
]
weight = torch.tensor(weight)

In [25]:
output = weight @ V
output

tensor([[2.0000, 7.0000, 1.5000],
        [2.0000, 8.0000, 0.0000],
        [2.0000, 7.8000, 0.3000]])

In [30]:
a = torch.tensor([[[1.0,2.0,3.0],
                 [4.0,5.0,6.0]],
                [[1.0,2.0,3.0],
                 [4.0,5.0,6.0]]])
a.shape

torch.Size([2, 2, 3])

In [34]:
mean = np.mean(a.numpy(), axis=(1, 2))
mean

array([3.5, 3.5], dtype=float32)

In [ ]:

var = np.var(a.numpy(), axis=(1,2))
div = np.sqrt(var+1e-05)
ln_out = (a-mean[:,None,None])/div[:,None,None]